name: java CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Make Gradlew Executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.1.4
        with:
          arguments: build
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: inyaa/inyaa-picture
          tags: latest
          registry: ccr.ccs.tencentyun.com
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop $(docker ps -a | grep "inyaa-picture" | awk '{print $1}')
            docker rm -f $(docker ps -a | grep inyaa-picture | awk '{print $1}')
            docker rmi $(docker images | grep inyaa-picture | awk '{print $3}')
            docker run -d -p 8082:8082 --name inyaa-picture --network inyaa --network-alias inyaa-picture ccr.ccs.tencentyun.com/inyaa/inyaa-picture:latest
